### ISSUE TITLE
I want to find room for bloodbraid elf (much funs) or too OP?

### ISSUE THREAD

**Issue by Luggsie** [davidchambers/cube#10]

**Comment by weakplayer** [comment]
what u wanna  cut tho.

**Comment by davidchambers** [comment]
:+1: from me. I want an aggressive creature-based Gruul deck to be viable, and we don't currently have many cards which reward playing these colours together. Can you suggest a card to cut?

**Comment by weakplayer** [comment]
that gruul 3 drop enchantment is good too, unsure if its in atm

**Comment by davidchambers** [comment]
[Fires of Yavimaya](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=23180)? It's in there.

**Comment by weakplayer** [comment]
ah sweet  :)

**Comment by Luggsie** [comment]
Not sure if this is fair in terms of card function but firespout as a
hybrid card for red/green seems out of place

If you felt this is crucial you could replace a red card with a sweeper.

**Comment by davidchambers** [comment]
I'd happily cut Firespout for Anger of the Gods if we can source one. This would allow us to add Bloodbraid Elf in place of a red creature.

**Comment by Luggsie** [comment]
What about breath of darigaaz or puroclasm or steam vents or something

theres a lot of choice.....  whats the sweep you played in your mono red in
the Welly nats?

Was uncounterable?

**Comment by weakplayer** [comment]
cut fiery justice maybe, kinda sucks

**Comment by Luggsie** [comment]
its pretty weak tight ... good against them token decks though :P

I dont mind seeing it removed, its not a great naya card anyways when you
have wild nacatyl in the cube.
