### ISSUE TITLE
increase size to 450 cards

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#106]
Why 450? It's useful for the total number of cards to be divisible by 45 and by 10. Imagine we're about to make packs for a six-player draft. It's easy to work out we need 6 × 45 = 270 cards, but we then need to perform arithmetic gymnastics to determine how many cards of each colour to include: 60 × 270 ÷ 405 = 36. With 450 cards the formula is straightforward: include ⅒ of the cards of each colour for each player.

```
              Before     After     Delta
White ........... 60 ...... 70 ..... +10
Blue ............ 60 ...... 70 ..... +10
Black ........... 60 ...... 70 ..... +10
Red ............. 60 ...... 70 ..... +10
Green ........... 60 ...... 70 ..... +10
Artifact ........ 45 ...... 40 ...... -5
Land ............ 60 ...... 60 ....... 0
========================================
                 405       450       +45
```

**Comment by maxcountryman** [comment]
I'm a fan of larger cubes for various reasons.

I would say however that building packs with a perfect color ratio is not necessary: MTGO builds cube packs totally randomly and that's also how I've built packs for my cube. I've yet to see any significant problem with this approach.
