### ISSUE TITLE
Replace absorb with supreme verdict or detention sphere

### ISSUE THREAD

**Issue by Luggsie** [davidchambers/cube#14]
Absorb is pretty boring and doesnt really add much to going blue/white

**Comment by weakplayer** [comment]
lol we're already talking about that

i suggest + random like BG garruk, and cut a blue card for distainful stroke or misdirection

**Comment by Luggsie** [comment]
Great minds :)

misdirection is a fair card..... I like it and its fun

**Comment by weakplayer** [comment]
i think stroke is stronger, and kinda goes with the morphs in the format

**Comment by Luggsie** [comment]
it probably is stronger - but free misdirection spells are fun.

the fact that it 'goes' with morph is a bit of a push lol.

**Comment by weakplayer** [comment]
whoops i actually meant miscalculation..

misdirection is cool tho, but i'd rather have either miscalculation or distainful stroke.  dave can pick which of the 3 tho

**Comment by Luggsie** [comment]
miscalculation is strong too.

**Comment by davidchambers** [comment]
We already have Mis<em>direction</em>, by the way.

**Comment by Luggsie** [comment]
Oh lol -

From the 2 Stroke is more of an owning and goes with morph so :P
