### ISSUE TITLE
add Hero's Downfall

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#16]
![Hero's Downfall](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=373575&type=card)

Does anyone have one?

**Comment by maxcountryman** [comment]
I have some extra copies of this if you still need one, @davidchambers.

**Comment by davidchambers** [comment]
Great! Drain Life and Corrupt are last-pick material, so I'd love to upgrade one of them to Hero's Downfall.
