### ISSUE TITLE
cut Tendrils of Agony

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#19]
The storm deck isn't fun to play against. I'm fine with combo decks in general, but storm involves lots of shuffling and very little interaction. I'd like to replace Tendrils with Liliana of the Veil.

**Comment by Luggsie** [comment]
If you remove tendrils then you should remove like gusthas scepter IMO -
make way for better artifact

**Comment by weakplayer** [comment]
agree with both, but i'd rather see the small liliana that the big one

**Comment by davidchambers** [comment]
[Liliana of the Veil](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=235597) _is_ the small one.

**Comment by davidchambers** [comment]
After drafting the cube for the first time, I believe @Luggsie would like to keep Tendrils. Is this correct?

**Comment by Luggsie** [comment]
I want to induce some storm. I think there needs to be cheaper supporting cards for it to be viable but that's more for discussion.  

i.e gusthas sceptre, frantic search. Etc. 

I think it's ok to be viable. Just probably want to monitor closely though as it shouldn't be auto win if you draft tendrils.

**Comment by weakplayer** [comment]
storm is never going to be an 'autowin' based on what i've seen

**Comment by davidchambers** [comment]
Let's keep Tendrils. The life gain is relevant to the Necro deck.
