### ISSUE TITLE
upgrade Oreskos Swiftclaw

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#2]
There are three strictly better creatures:
- [Accorder Paladin](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=213818)
  
  ![Accorder Paladin](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=213818&type=card)
- [Daring Skyjek](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=366251)
  
  ![Daring Skyjek](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=366251&type=card)
- [Spirit of the Labyrinth](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=378399)
  
  ![Spirit of the Labyrinth](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=378399&type=card)

Do we want a solid combat ability or an occasionally very powerful but usually irrelevant ability?

**Comment by weakplayer** [comment]
yeah there's also the 2W 3/1 first strike u can pay 2 life instead of W, but overall i think the battlecry man is the strongest

**Comment by Luggsie** [comment]
Not quite the same but what about going for grizzly bear that has prowess and gains life link?

I think prowess is good for the game. Less aggro that the battle cry by a long way and doesn't synergies with token madness but more fun. 

Token already strong archetype in this cube.

**Comment by davidchambers** [comment]
Seeker of the Way is a great idea. It's good in white weenie but also in more controlling decks. I'd like to make room for Monastery Swiftspear as well.

**Comment by weakplayer** [comment]
yeah agree with adding both
