### ISSUE TITLE
Add Batterskull

### ISSUE THREAD

**Issue by Luggsie** [davidchambers/cube#20]
Or do we think this is too kinda OP and dry in limited... it basically does too much?

**Comment by davidchambers** [comment]
I haven't played with or against this card much, so I don't know whether it leads to interesting games.

**Comment by weakplayer** [comment]
i personally dont like playing with it, and don't like being on the receiving end of it either haha

**Comment by davidchambers** [comment]
I'll close this issue. Feel free to reopen it, @Luggsie, if you're very keen on including Batterskull.
