### ISSUE TITLE
add Chandra, Pyromaster

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#22]
![Chandra, Pyromaster](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=370637&type=card)

I suggest cutting Shrapnel Blast as there aren't enough cheap, aggressive artifacts to support it.

**Comment by weakplayer** [comment]
fair enough, i prefer chandra over sarkhan fwiw (if can't fit both/don't want that many PW)

**Comment by davidchambers** [comment]
> i prefer chandra over sarkhan fwiw (if can't fit both/don't want that many PW)

I do too.
