### ISSUE TITLE
add Tezzeret the Seeker

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#24]
![Tezzeret the Seeker](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=174912&type=card)

What shall we cut?

**Comment by weakplayer** [comment]
muck undo imo, i'm not into cards that are purely for the sideboard... and i don't think drafting a strat where u cast it on your own boys is that viable in this

**Comment by Luggsie** [comment]
I don't like him.

**Comment by davidchambers** [comment]
> I don't like him.

Him being Tezzeret?

**Comment by weakplayer** [comment]
what's your beef luggsie?

**Comment by weakplayer** [comment]
i'd rather this boy than heaps of the other plainswalkers

**Comment by Luggsie** [comment]
I just think the core objective was a cube that encouraged or revolved around combat or honest battles for the most part. 

Not something I voted for but learnt after chatting with Dave. 

With that in mind I think there are better PWs that achieve a step towards that direction than this man. 

Artefact.dec usually isnt very interactive and can be OP. Even the inclusion of academy is questionable IMO. 

Just my 2c

**Comment by weakplayer** [comment]
i don't think artefacts are that strong atm in this cube, its not like this dude comes down and can use the ulti straight up, u need some kind of board advantage + the artifacts in play, its not that easy imo..

what u think dave?

**Comment by Luggsie** [comment]
If that's the case then surely there are better cards (if he's not much use - too narrow)

**Comment by davidchambers** [comment]
> i'd rather this boy than heaps of the other plainswalkers

There's not a single [plainswalker](http://gatherer.wizards.com/Pages/Search/Default.aspx?action=advanced&text=+[Plainswalk]&type=+[Creature]) I'd pick over this fellow. :P

> I just think the core objective was a cube that encouraged or revolved around combat or honest battles for the most part.

Combat should be central, though the most important thing is that the decks be interactive. I don't want to see Inkwell Leviathan getting tinkered into play on turn two. Tezzeret is more interesting, as he's likely to fetch defensive, interactive cards in many cases.

> surely there are better cards (if he's not much use - too narrow)

He is narrow. I worry that @weakplayer is to some extent crafting the deck he'd like to draft in advance, as Shaun once did. I'm okay with this, because the suggestions are usually well reasoned, but I do worry a bit about the colours which aren't receiving as much attention.

**Comment by weakplayer** [comment]
mate i just want him as an AWC for land.dec xD

**Comment by weakplayer** [comment]
but its cool if u guys dont like him

**Comment by Luggsie** [comment]
Depends on the format. 

Jace is widely regarded as best but that's beside the point.

 I think you guys have a soft spot for him in which case that's fine. I do think we want to avoid artifact.dec though. It generally break rules of magic.

**Comment by weakplayer** [comment]
so you'd muck the tolarian academy then?

cole will cry

**Comment by davidchambers** [comment]
[Cole's HoM 3 decklist](http://blog.mtg-apps.com/hom-3-decklists/#cole_swannack) is informative. This deck is undoubtedly an artifact deck, yet Cole's matches (such as the [final](http://blog.mtg-apps.com/hom-3-match-reports/#final) against James) were interesting, with each game playing out differently. I believe by withholding Tinker and possibly other cards it's possible to have an artifact deck which does unfair things sometimes but which isn't broken. I'm just not sure whether Tezzeret is one of the cards we should be withholding.

**Comment by Luggsie** [comment]
We'll if it was up to me Id muck it

Seriously it's always up to no good. To be honest though I think it's fine in a cube that is balanced I think it's of a level that puts it ahead of other cards/colours ATM

**Comment by davidchambers** [comment]
I'm saying no to Tezzeret. It's a very powerful card in exactly one deck.

**Comment by weakplayer** [comment]
all good
