### ISSUE TITLE
add Ajani Vengeant

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#26]
![Ajani Vengeant](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=174852&type=card)

What shall we cut? Rhox War Monk?

**Comment by Luggsie** [comment]
Monk is weak tight. 

Concerned we have too many planes walkers and not enough cards that interact with them?

**Comment by davidchambers** [comment]
> Concerned we have too many planes walkers and not enough cards that interact with them?

I agree. See #16, #30, and #31.
