### ISSUE TITLE
add Ashiok, Nightmare Weaver

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#27]
![Ashiok, Nightmare Weaver](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=373500&type=card)

**Comment by weakplayer** [comment]
i think ashiok is a bit weak in cube, sideboard card imo

**Comment by davidchambers** [comment]
Decking is not viable? Is Ashiok is too difficult to protect?

**Comment by weakplayer** [comment]
i guess it could be viable idk, i just generally don't play vs many creatures or have many in the cubes i've played, and i always see ashiok hanging around the bottom of packs..

but don't really know, he's decent in std contructed haha

**Comment by davidchambers** [comment]
> i just generally don't play vs many creatures or have many in the cubes i've played

This makes Ashiok significantly _better_, in my view. If one's opponent is not playing many creatures she'll have more trouble getting Ashiok off the board. Even when one does hit a creature it's often correct to keep milling anyway.

I'm keen to include this card now because I'm interested in finding out whether or not it's good.

**Comment by weakplayer** [comment]
fair enough :)

**Comment by davidchambers** [comment]
Closing since the cube no longer contains multicoloured cards.
