### ISSUE TITLE
add Domri Rade

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#28]
![Domri Rade](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=366367&type=card)

**Comment by weakplayer** [comment]
how about mucking a card from each colour to add 5 more gold cards?

**Comment by davidchambers** [comment]
> how about mucking a card from each colour to add 5 more gold cards?

This is the current breakdown:

```
White ........... 60
Blue ............ 60
Black ........... 60
Red ............. 60
Green ........... 60
Multicolored .... 30
Artifact ........ 48
Land ............ 60
====================
                 438
```

There's nothing special about 438 or any of the other numbers. There is something pleasing about the number 60, though, so I'd like to keep 60 cards of each colour. We can certainly increase the number of multicolored cards if we want to.

**Comment by Luggsie** [comment]
I know you don't think it's a big deal but you should reconsider balancing gold cards for guilds.

**Comment by davidchambers** [comment]
> I know you don't think it's a big deal but you should reconsider balancing gold cards for guilds.

I agree this is worth attempting. It's blurry, though. Is a `{W}{U}` card "whiter" than a `{W}{U}{B}` card by virtual of being half white rather than a third white? Is Supreme Verdict more white than blue? Should we take into account a card like Tin Street Hooligan which is technically one colour but which has a mana symbol of a different colour in its text box?

The cube needn't have an even colour distribution; drafting strategy should adjust accordingly. That said I do think it's preferable for the cube to feature a roughly even distribution of colours.

**Comment by weakplayer** [comment]
speaking of supreme verdict, do u guys like quicken?

**Comment by davidchambers** [comment]
I'm rather fond of Quicken. It costs `{U}`, draws a card, and does something surprising. What's not to like? :)

I'll add it if you can work out what to cut.

**Comment by weakplayer** [comment]
the mill 2 draw a card is an easy swap imo

**Comment by Luggsie** [comment]
Show and tell?

Eldrazi?

**Comment by davidchambers** [comment]
Closing since the cube no longer contains multicoloured cards.
