### ISSUE TITLE
add Lingering Souls

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#3]
![Lingering Souls](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=262695&type=card)

I'm not sure what to cut, but I really want to include this card. Cloudgoat Ranger perhaps, or Geist-Honored Monk.

**Comment by weakplayer** [comment]
i actually like the goat and monk over this, that said if you bring in anthem, and that artifact with a similar effect, then cut the cloudgoat for this (just because the goat has been in more cubes than the monk hehe)

**Comment by weakplayer** [comment]
having said that, you definietely don't want to give white weenie too much gas (just cos its boring :p)

**Comment by davidchambers** [comment]
While Spectral Procession is very much a white weenie card, Lingering Souls is also great _against_ white weenie. Lingering Souls was one of my few outs to my opponent's early Spectral Procession in a draft a few days ago.

Battle Screech + Spectral Procession + Cloudgoat Ranger + Geist-Honored Monk is a bit much, though. ;)

**Comment by weakplayer** [comment]
bin the goat off imo :)

**Comment by Luggsie** [comment]
Geist is worse

**Comment by davidchambers** [comment]
> Geist is worse

I don't think any of us will argue otherwise. I believe @weakplayer favours cutting CGR because he's played with it in a few cubes already.

I (slightly) favour cutting CGR, but for a different reason: in white we currently have bird, kithkin, soldier, and spirit tokens; cutting CGR would reduce administrative complexity.
