### ISSUE TITLE
Replace thoughtscour with confiscate

### ISSUE THREAD

**Issue by Luggsie** [davidchambers/cube#33]

**Comment by davidchambers** [comment]
:+1: for adding Confiscate.

I'm not sure Thought Scour is the best card to cut, though. It works well with the likes of Nimble Mongoose, Werebear, and Roar of the Wurm.

Other options:
- Control Magic
- Diminishing Returns
- Intuition
- Treachery
- Fathom Seer

**Comment by Luggsie** [comment]
Probably right - I vote for diminishing returns then
