### ISSUE TITLE
Replace Pyromancers Gauntlet with winter orb

### ISSUE THREAD

**Issue by Luggsie** [davidchambers/cube#34]
A red only card in the artefact slot? would like to see a more generic card that supports more archetypes here.

Winter orb is one possibility with prison/weenie being more achievable.

**Comment by davidchambers** [comment]
We should cut Gustha's Scepter before Pyromancer's Gauntlet. I'm happy to add Winter Orb if others agree it's good for the game.

**Comment by Luggsie** [comment]
we have geddon, balance, and hikori already?

I did think it might be a bit too nasty.

**Comment by davidchambers** [comment]
Winter Orb is more versatile than Hokori since it can also be played in artifact-heavy blue decks, so there's an argument for its inclusion. The question is whether games involving Winter Orb are interesting. I tend to think they are, as they're constrained in an unusual way.

**Comment by Luggsie** [comment]
I think its interesting as its a card that requires investment during deck
drafting and building phases specifically.

A card that's of little value unless you have a strategy that supports it
which makes it interesting. Just adds a little more to the mix than
creature/removal

**Comment by weakplayer** [comment]
i like orb, but we don't want too many of those kind of effects...

that said i'd like to see something cut for nether void :p

**Comment by davidchambers** [comment]
> that said i'd like to see something cut for nether void

Sure. Would you mind checking that we have one, @Luggsie?
