### ISSUE TITLE
add Natural Order

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#38]
![Natural Order](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=3671&type=card)

Thoughts?

**Comment by Luggsie** [comment]
Lol off topic but thoughts on squirrels nest?

**Comment by weakplayer** [comment]
its a bit underwhelming with the current creatures, but a fine card.

also off topic, but i'd really like to add the green, black, and blue devotion gods, also the nightveil spectre

**Comment by davidchambers** [comment]
> its a bit underwhelming with the current creatures, but a fine card.

Do you two like the idea of cutting Restock? If not, what do you suggest?

> i'd really like to add the green, black, and blue devotion gods, also the nightveil spectre

You should open an issue for this so it doesn't get forgotten.

**Comment by weakplayer** [comment]
yeah just don't know how to do it haha, i'll be back in a couple hours though, i'll sort it out then

**Comment by davidchambers** [comment]
There's a "New issue" button at https://github.com/davidchambers/cube/issues. I opened issues for the gods, by the way.

**Comment by Luggsie** [comment]
Is weak player Matt or kaki? I just assumed it was kaki from name and language used. 

However the knowledge of mtg cards is deep and I'm surprised if kaki knows as many of the cards and names as much as the conversation has been using.

**Comment by davidchambers** [comment]
I too am impressed by the depth of @weakplayer's knowledge.

**Comment by weakplayer** [comment]
haha, been doing magic online holiday cubingtons :)

u should get in on it daz, pretty sweet, and cheap compared to some of the other online draft formats

**Comment by Luggsie** [comment]
Will have a look tonight

**Comment by Luggsie** [comment]
let me know what your ltbg online names are... mine is VexumNZ

**Comment by weakplayer** [comment]
cool, i'm just kakitee

**Comment by davidchambers** [comment]
I'm SOANGRY.

**Comment by Luggsie** [comment]
Played my first one drafted a mono red deck. Crushed my first opponent then had to drop. 

Easy game.
