### ISSUE TITLE
add Aven Mindcensor

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#39]
![Aven Mindcensor](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=136204&type=card)

I don't love the illustration, but the ability blunts some of the very powerful cards we're considering adding (Tezzeret and Natural Order).

**Comment by weakplayer** [comment]
overall its quite a weak card imo, just another sideboard boy hanging around

**Comment by Luggsie** [comment]
Too narrow

What about the new one? He's a 2/1 flyer? Got a bit more bite

**Comment by davidchambers** [comment]
I don't share your aversion to sideboard cards, @weakplayer. In cube one tends to end up with 30+ playables. A narrow sideboard card (which is also a tutor target) is more useful than the 33rd playable.

I'll close this issue, though, as the response was not positive. :)

**Comment by weakplayer** [comment]
the new one is actually pretty cool, prevents creature's come into play effects same cost and stats
