### ISSUE TITLE
Dudes

### ISSUE THREAD

**Issue by EnchanteChang** [davidchambers/cube#53]
As I said in the email, I think the little creatures are under powered. You have amazing spells like Balance, Opposition, VT/DT etc and then you have guys like Goblin Cadets, Savannah Lions.

Need a few more 187 dudes like Sex Monkeys.

**Comment by davidchambers** [comment]
We should also increase the number of two-power one-drops and aggressive two-drops.

**Comment by EnchanteChang** [comment]
Not sure if two power one drops is the answer. The guys just need to do something. Mother of Runes is a great one drop, but I don't think she does that much in _this_ cube.

**Comment by davidchambers** [comment]
The situation is significantly better now.
