### ISSUE TITLE
add Elspeth, Sun's Champion

### ISSUE THREAD

**Issue by davidchambers** [davidchambers/cube#6]
![Elspeth, Sun's Champion](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=373649&type=card)

@weakplayer and I discussed this earlier. The cards we discussed cutting are Serra Angel and Exalted Angel. Serra Angel was a nostalgic inclusion and could be cut. I'm reluctant to cut Exalted Angel as face-down creatures get less interesting as the number of possibilities decreases.

**Comment by weakplayer** [comment]
yeah agree, if you're gonna do morphs have a little range going

**Comment by Luggsie** [comment]
Of course. To be honest though the number that are in is on the low side already though. 

Also swap molten core manticore for myr battle sphere. Matt griff and I have some nolstelga with the myr :) he's vintage!

**Comment by Luggsie** [comment]
Also elspeth is clearly good but so boring. Also the token theme is already so strong in white?

**Comment by Luggsie** [comment]
Btw reason for molten core out is you already have OG masticore.

**Comment by weakplayer** [comment]
agree with the battlesphere total boss.  i thought it was in?

**Comment by davidchambers** [comment]
> Also elspeth is clearly good but so boring. Also the token theme is already so strong in white?

Good point. Just because a card's very good doesn't mean it deserves to be included. Serra Angel can keep her spot for now. :)
